### ISSUE TITLE
Running coretest overwrites /var/run/etcd/bootstrap.disco

### ISSUE THREAD

**Issue by bcwaldon** [coreos/coretest#17]
As documented in the test at https://github.com/coreos/coretest/blob/03512eea351cd7903b070b4969c1dd764a27928b/cloudinit_test.go#L60, we expect coreos-cloudinit to make a change to `/var/run/etcd/bootstrap.disco`. This isn't exactly friendly to people trying to debug running systems.

**Comment by bgilbert** [comment]
coretest has been replaced by [kola](https://github.com/coreos/mantle), and kola's architecture shouldn't be susceptible to this issue.  Closing.
