### ISSUE TITLE
Separate cluster-level from local tests

### ISSUE THREAD

**Issue by bcwaldon** [coreos/coretest#39]
It would be valuable to separate the test suite into tests that assert things at the cluster level (like fleet and etcd), from tests that assert things about the local machine. This should be as simple as using a common prefix in the test names such as "TestCluster..." or "TestLocal...".

**Comment by bgilbert** [comment]
coretest is deprecated in favor of [kola](https://github.com/coreos/mantle), where this seems less relevant.  Closing.
