### ISSUE TITLE
Split tests into groups based on external dependencies

### ISSUE THREAD

**Issue by marineam** [coreos/coretest#8]
It is generally asking for a world of pain to depend on the external network and the internet. Flaky tests that fail due to things outside of ones control just serves as training to ignore tests entirely. Running integration tests against external services is still important but should be in a separate test suite so they can be triaged differently. For example:
- Split docker test into two, one that imports a container bundled with coretest, one that pulls from the docker index.
- Split tlsdate into two, one that hits a ssl server built into coretest, another that uses an external server.

This cluster-wide tests really covered yet but as coretest expands tests that cover the local machine vs tests that cover an entire cluster vs tests that depend on external services like etcd discovery would all be separate suites.

**Comment by bgilbert** [comment]
Moved part of this to https://github.com/coreos/mantle/issues/572, and the rest doesn't seem relevant to current kola.
